# fly.toml file generated for lrsic-tiles-server on 2023-03-14T23:14:17-04:00

app = "lrsic-tiles-server"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"
processes = []

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
